# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoEasy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoEasy
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  project '/Users/prakharsrivastava/Desktop/GoEasy/GoEasy/GoEasy/GoEasy.xcodeproj'
end
